shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach -t base || tmux new -s base"

title: Terminal 

font:
  normal:
    family: JetBrainsMono Nerd Font 
    style: Regular

window:
  opacity: 0.8
  startup_mode: Windowed 

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true
  thickness: 0.15

# Colors (Hyper)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  cursor:
    text: '0xF81CE5'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xFFFFFF'

key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }

draw_bold_text_with_bright_colors: true
