version: '3'
services:
  ubuntu:
    image: ubuntu:22.04
    volumes:
      - .:/root/.dotfiles
    command: bash -c "sed -i 's|http://archive|http://id.archive|g' /etc/apt/sources.list && tail -f /dev/null"
    restart: always