version: '3'
services:
  ubuntu:
    image: ubuntu:22.04
    volumes:
      - .:/root/.dotfiles
    command: |
      sed -i 's|http://|http://id.|g' /etc/apt/sources.list
      tail -f /dev/null
    restart: always