console_title_template = '{{ .Shell }} in {{ .Folder }}'
version                = 3
final_space            = true

[palettes]
template = 'material'

  [palettes.list]
    [palettes.list.dracula]
    black   = '#44475A'
    blue    = '#9C6FCF'
    cyan    = '#6AC5D3'
    green   = '#2FD651'
    magenta = '#DE559C'
    orange  = '#DE9442'
    pink    = '#ff79c6'
    purple  = '#bd93f9'
    red     = '#DE312B'
    white   = '#D7D4C8'
    yellow  = '#D0D662'

    [palettes.list.gruvbox]
    black   = '#282828'
    blue    = '#458588'
    cyan    = '#83A598'
    green   = '#8EC07C'
    magenta = '#D3869B'
    orange  = '#FE8019'
    pink    = '#FB4934'
    purple  = '#D3869B'
    red     = '#CC241D'
    white   = '#EBDBB2'
    yellow  = '#FABD2F'

    [palettes.list.material]
    black   = '#212121'
    blue    = '#2196F3'
    cyan    = '#00BCD4'
    green   = '#4CAF50'
    magenta = '#E91E63'
    orange  = '#FF9800'
    pink    = '#E91E63'
    purple  = '#9C27B0'
    red     = '#F44336'
    white   = '#FAFAFA'
    yellow  = '#FFEB3B'

    [palettes.list.material_dark]
    black   = '#000000'
    blue    = '#1976D2'
    cyan    = '#0097A7'
    green   = '#388E3C'
    magenta = '#D81B60'
    orange  = '#F57C00'
    pink    = '#C2185B'
    purple  = '#7B1FA2'
    red     = '#D32F2F'
    white   = '#E0E0E0'
    yellow  = '#FBC02D'

    [palettes.list.material_light]
    black   = '#CFD8DC'
    blue    = '#BBDEFB'
    cyan    = '#B2EBF2'
    green   = '#C8E6C9'
    magenta = '#F48FB1'
    orange  = '#FFE0B2'
    pink    = '#F8BBD0'
    purple  = '#E1BEE7'
    red     = '#FFCDD2'
    white   = '#FFFFFF'
    yellow  = '#FFF9C4'

    [palettes.list.nord]
    black   = '#2E3440'
    blue    = '#5E81AC'
    cyan    = '#88C0D0'
    green   = '#A3BE8C'
    magenta = '#B48EAD'
    orange  = '#D08770'
    pink    = '#BF616A'
    purple  = '#B48EAD'
    red     = '#BF616A'
    white   = '#ECEFF4'
    yellow  = '#EBCB8B'

    [palettes.list.solarized]
    black   = '#073642'
    blue    = '#268BD2'
    cyan    = '#2AA198'
    green   = '#859900'
    magenta = '#D33682'
    orange  = '#CB4B16'
    pink    = '#D33682'
    purple  = '#6C71C4'
    red     = '#DC322F'
    white   = '#FDF6E3'
    yellow  = '#B58900'

[secondary_prompt]
template   = '❯❯ '
foreground = 'magenta'
background = 'transparent'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}p:red{{end}}',
  '{{if eq .Code 0}}p:green{{end}}',
]

[[blocks]]
type      = 'prompt'
alignment = 'left'

  [[blocks.segments]]
  style    = 'plain'
  template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}}'
  type     = 'os'

  [[blocks.segments]]
  style      = 'plain'
  template   = ' {{ if eq .Env.HOME .AbsolutePWD }} {{ else }} {{ end }}{{ .Path }}'
  foreground = 'p:blue'
  background = 'transparent'
  type       = 'path'

    [blocks.segments.properties]
    style = 'full'

  [[blocks.segments]]
  style      = 'plain'
  template   = ' <p:white>on</> {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<p:blue>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<p:yellow>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
  foreground = 'p:green'
  type       = 'git'

    [blocks.segments.properties]
    fetch_status        = true
    fetch_upstream_icon = true
    source              = 'cli'

[[blocks]]
type      = 'prompt'
alignment = 'right'

  [[blocks.segments]]
  style      = 'plain'
  template   = 'go{{ .Full }} '
  foreground = 'p:cyan'
  type       = 'go'

  [[blocks.segments]]
  style      = 'plain'
  template   = 'node{{ .Full }} '
  foreground = 'p:green'
  type       = 'node'

  [[blocks.segments]]
  style      = 'plain'
  template   = 'py{{ .Full }} '
  foreground = 'p:yellow'
  type       = 'python'

  [[blocks.segments]]
  style      = 'plain'
  template   = ' ⎈ {{ (split "/" .Cluster)._1 }}{{ if .Namespace }} :: {{ .Namespace }}{{ end }} '
  foreground = 'p:blue'
  type       = 'kubectl'
  alias      = 'k8s'

  [[blocks.segments]]
  style      = 'plain'
  template   = '☁️ {{ if .Env.AWS_PROFILE }}{{ .Env.AWS_PROFILE }}{{ end }}{{ if .Env.AWS_SSO_ROLE_NAME }}{{ .Env.AWS_SSO_ROLE_NAME }}{{ end }}@{{ if .Env.AWS_SSO_ACCOUNT_ID }}{{ .Env.AWS_SSO_ACCOUNT_ID }}:{{ end }}{{ if .Region }}{{ .Region }}{{ end }} '
  foreground = 'p:orange'
  type       = 'aws'

  [[blocks.segments]]
  style      = 'diamond'
  template   = '{{ if .SSHSession }} {{ .UserName }}@{{ .HostName }}{{ end }}'
  foreground = '#ffffff'
  type       = 'session'

[[blocks]]
type     = 'rprompt'
overflow = 'hidden'

  [[blocks.segments]]
  style      = 'plain'
  template   = '{{ .FormattedMs }}'
  foreground = 'p:yellow'
  background = 'transparent'
  type       = 'executiontime'

    [blocks.segments.properties]
    threshold = 1000

  [[blocks.segments]]
  style = 'plain'
  foreground = '#ffffff'
  type = 'status'
  foreground_templates = [
    '{{if gt .Code 0}}p:red{{end}}',
    '{{if eq .Code 0}}p:green{{end}}',
  ]

    [blocks.segments.properties]
    always_enabled  = true
    status_template = '{{ if .Error }}✘ {{ reason .Code }}{{ else }}✔{{ end }}'

[[blocks]]
type      = 'prompt'
alignment = 'left'
newline   = true

  [[blocks.segments]]
  style = 'plain'
  template = '🤔❯'
  background = 'transparent'
  type = 'text'
  foreground_templates = [
    '{{if gt .Code 0}}p:red{{end}}',
    '{{if eq .Code 0}}p:green{{end}}',
  ]
